#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

umask 077

SETUP_REPOSITORY="Graindevue/graindevue"
SOURCE_REPOSITORY="Graindevue/sandy"
SETUP_APP_OWNER="Graindevue"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) SETUP_REPOSITORY="$2"; shift 2 ;;
    --source) SOURCE_REPOSITORY="$2"; shift 2 ;;
    --app-owner) SETUP_APP_OWNER="$2"; shift 2 ;;
    --help)
      printf 'Usage: bash scripts/setup-actions.sh [--repo owner/repo] [--source owner/sandy] [--app-owner organization]\n'
      exit 0 ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; exit 1 ;;
  esac
done
[[ "$SETUP_REPOSITORY" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || {
  printf 'Invalid target repository\n' >&2; exit 1;
}
[[ "$SOURCE_REPOSITORY" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || {
  printf 'Invalid source repository\n' >&2; exit 1;
}
[[ "$SETUP_APP_OWNER" =~ ^[A-Za-z0-9_.-]+$ ]] || {
  printf 'Invalid GitHub App organization owner\n' >&2; exit 1;
}
SETUP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$SETUP_ROOT/.config/actions-setup.env"
mkdir -p "$SETUP_ROOT/.config"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
export GH_REPO="$SETUP_REPOSITORY"
command -v gh >/dev/null || { printf 'Install GitHub CLI first: https://cli.github.com/\n' >&2; exit 1; }
command -v codex >/dev/null || {
  printf 'Install Codex first: npm install --global @openai/codex@0.162.0\n' >&2; exit 1;
}
gh auth status >/dev/null 2>&1 || { printf 'Run gh auth login first.\n' >&2; exit 1; }
[[ "$(gh api "repos/$SETUP_REPOSITORY" --jq .private)" == true ]] || {
  printf 'Codex subscription auth requires a private repository.\n' >&2; exit 1;
}
# The agent provisions this environment and repository secrets before handing
# off this wizard. Only human UI grants, PAT creation and device login remain.
gh api "repos/$SETUP_REPOSITORY/environments/sandy-codex" >/dev/null || {
  printf 'The sandy-codex environment must be provisioned first (private environments require a supported plan).\n' >&2
  exit 1
}

banner "Sandy: human-only GitHub Actions setup"

stage "Grant the App permission to maintain the rotating Codex session"
open_url "https://github.com/organizations/$SETUP_APP_OWNER/settings/apps/agent-sandy/permissions"
step "Open Repository permissions, grant Environments: Read and write, then save."
note "Environment secrets use Environments permission. Repository Secrets permission alone is insufficient."
open_url "https://github.com/organizations/${SETUP_REPOSITORY%%/*}/settings/installations"
step "Open the agent-sandy installation, review the new permission request and accept it."
note "For a personal target repository, use https://github.com/settings/installations instead."
pause "Press Enter once the installation has accepted Environments: Read and write."

stage "Authorize access to the private cross-owner Sandy source"
if [[ "$(gh secret list --repo "$SETUP_REPOSITORY" --json name --jq 'any(.[]; .name == "SANDY_SOURCE_SSH_KEY")')" == true ]]; then
  say "A SANDY_SOURCE_SSH_KEY deploy key is already configured for the source checkout."
  note "It must be registered on $SOURCE_REPOSITORY with read-only access."
  note "Checkout removes the private key before any reviewed code runs."
  pause "Press Enter to keep the configured deploy key."
else
  say "Preferred: install agent-sandy on $SOURCE_REPOSITORY so it can mint short-lived read-only tokens."
  say "Alternative: provide a fine-grained personal access token as SANDY_SOURCE_TOKEN."
  ask SANDY_SOURCE_AUTH "Choose app or pat [Enter defaults to app]:"
  SANDY_SOURCE_AUTH="${SANDY_SOURCE_AUTH:-app}"
  write_env SANDY_SOURCE_AUTH "$SANDY_SOURCE_AUTH"
  case "$SANDY_SOURCE_AUTH" in
    app)
      open_url "https://github.com/apps/agent-sandy/installations/new"
      step "Choose the ${SOURCE_REPOSITORY%%/*} account and install agent-sandy on ${SOURCE_REPOSITORY##*/}."
      step "Select only that source repository; no personal access token is needed."
      note "The workflow restricts the source installation token to Contents: Read-only."
      note "If the org-owned App cannot be installed outside its owner, use the PAT alternative."
      note "A repository SANDY_SOURCE_TOKEN secret overrides App access; remove it to use this path."
      pause "Press Enter once the App installation can access $SOURCE_REPOSITORY."
      ;;
    pat)
      open_url "https://github.com/settings/personal-access-tokens/new"
      step "Create a fine-grained personal access token with resource owner ${SOURCE_REPOSITORY%%/*}."
      step "Select only ${SOURCE_REPOSITORY##*/}; grant Contents: Read-only (Metadata is automatic)."
      step "Choose an expiration and record when the token must be replaced."
      ask_secret SANDY_SOURCE_TOKEN "Paste the new read-only token:"
      [[ -n "$SANDY_SOURCE_TOKEN" ]] || { printf 'A source token is required.\n' >&2; exit 1; }
      write_env SANDY_SOURCE_TOKEN "$SANDY_SOURCE_TOKEN"
      chmod 600 "$ENV_FILE"
      set_secret SANDY_SOURCE_TOKEN "$SANDY_SOURCE_TOKEN"
      # Refuse to continue after a failed upload so the closing summary is accurate.
      (( ${#SKIPPED[@]} == 0 )) || exit 1
      ;;
    *) printf 'Choose app or pat.\n' >&2; exit 1 ;;
  esac
fi

stage "Create a separate Codex login for the serialized CI stream"
open_url "https://learn.chatgpt.com/docs/auth/ci-cd-auth"
step "Read the account-auth procedure and confirm this CI stream can use your subscription."
note "Review tokens count toward your ChatGPT plan limits; check its available capacity."
note "This creates a new login. Your personal ~/.codex/auth.json is never read or copied."
note "Do not use this CI login for another machine, repository or concurrent workflow."
confirm "Create a dedicated login and replace this CI stream's auth secret?" || exit 0
SETUP_LOGIN_DIR="$(mktemp -d "$SETUP_ROOT/.config/codex-ci-login.XXXXXX")"
trap 'rm -rf "$SETUP_LOGIN_DIR"' EXIT
chmod 700 "$SETUP_LOGIN_DIR"
printf 'cli_auth_credentials_store = "file"\nforced_login_method = "chatgpt"\n' > "$SETUP_LOGIN_DIR/config.toml"
chmod 600 "$SETUP_LOGIN_DIR/config.toml"
CODEX_HOME="$SETUP_LOGIN_DIR" codex login --device-auth
node --input-type=module - "$SETUP_LOGIN_DIR/auth.json" <<'JS'
import { readFileSync } from 'node:fs';
const auth = JSON.parse(readFileSync(process.argv[2], 'utf8'));
if (auth.auth_mode !== 'chatgpt' || !auth.tokens?.refresh_token || !auth.tokens?.access_token) {
  throw new Error('Login did not produce file-backed, managed ChatGPT auth');
}
JS
gh secret set CODEX_AUTH_JSON --repo "$SETUP_REPOSITORY" --env sandy-codex < "$SETUP_LOGIN_DIR/auth.json"
WRITTEN_SECRET+=("sandy-codex/CODEX_AUTH_JSON")
# Prevent later use of this seed copy from rotating the runner's refresh token.
rm -rf "$SETUP_LOGIN_DIR"
trap - EXIT
say "The dedicated login is now stored only in the sandy-codex environment."
note "CODEX_AUTH_JSON must never also be configured as a repository/organization secret."
finish
